### ISSUE TITLE
Add top level README.md file

### ISSUE THREAD

**Issue by mithro** [The-OpenROAD-Project/OpenDB#1]
You seem to be missing that....

**Comment by abdelrahmanhosny** [comment]
This is addressed in https://github.com/The-OpenROAD-Project/OpenDB/commit/4cc616a60867ce8bbd184322b6561b9b82b3ff7c

Currently in the `develop` branch and will be merged to master soo.

**Comment by abdelrahmanhosny** [comment]
Changes merged to `master`
