### ISSUE TITLE
Installation of Dependencies to be added to README.md

### ISSUE THREAD

**Issue by born-2learn** [The-OpenROAD-Project/OpenDB#101]
The [README.md](https://github.com/The-OpenROAD-Project/OpenDB/blob/master/README.md) file in the project does not have the instructions to install the dependencies `flex`, `bison`, `tcl-dev` to build the project. I would like to add it to the README.md file.

**Comment by maliberty** [comment]
You can see all the dependencies for centos7 by looking in the Dockerfile.  Is it sufficient to put a reference to it in the README?

**Comment by born-2learn** [comment]
Dependencies for centos7 are well defined in the docker image. 
I was referring to the builds from scratch on other systems( eg. Ubuntu).
I can add that to the README.

**Comment by maliberty** [comment]
We now have a ubuntu dockerfile as well.  I don't see anything further to do here.
