### ISSUE TITLE
libtcl library shouldn't be used

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenDB#119]
https://github.com/The-OpenROAD-Project/OpenDB/blob/master/src/swig/tcl/CMakeLists.txt#L20

Please use the library returned by FindTCL.cmake

**Comment by maliberty** [comment]
This is resolved on the 'openroad' branch which represents the current development head.  'master' is used for a stable release point and is rather old at this time.

https://github.com/The-OpenROAD-Project/OpenDB/blob/openroad/CMakeLists.txt#L22
