### ISSUE TITLE
Compilation errors builing cpp application

### ISSUE THREAD

**Issue by adhocmaster** [The-OpenROAD-Project/OpenDB#121]
Hi all,

I tried making an application. My Makefile is:
	INC = -I/home/muktadir/cse220/OpenDB/include/opendb
	LIB = /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a

	all: app

	app: includeText.cpp ${LIB}
		c++ -Wall -pedantic -g $(INC) includeText.cpp -o includeText ${LIB}

	clean:
		rm -f app

**And I am getting these errors:**

  c++ -Wall -pedantic -g -I/home/muktadir/cse220/OpenDB/include/opendb includeText.cpp -o includeText /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbDatabase.cpp.o): In function `odb::operator>>(odb::dbIStream&, odb::_dbDatabase&)':
  dbDatabase.cpp:(.text+0x169d): undefined reference to `odb::ZException::ZException(char const*, ...)'
  dbDatabase.cpp:(.text+0x16a4): undefined reference to `odb::ZException::~ZException()'
  dbDatabase.cpp:(.text+0x16ff): undefined reference to `odb::ZException::ZException(char const*, ...)'
  dbDatabase.cpp:(.text+0x1706): undefined reference to `odb::ZException::~ZException()'
  dbDatabase.cpp:(.text+0x175e): undefined reference to `odb::ZException::ZException(char const*, ...)'
  dbDatabase.cpp:(.text+0x1765): undefined reference to `odb::ZException::~ZException()'
  dbDatabase.cpp:(.text+0x17be): undefined reference to `odb::ZException::ZException(char const*, ...)'
  dbDatabase.cpp:(.text+0x17c5): undefined reference to `odb::ZException::~ZException()'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbDatabase.cpp.o): In function `odb::dbDatabase::writeTech(_IO_FILE*)':
  dbDatabase.cpp:(.text+0x255c): undefined reference to `odb::ZException::ZException(char const*, ...)'
  dbDatabase.cpp:(.text+0x2563): undefined reference to `odb::ZException::~ZException()'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbDatabase.cpp.o): In function `odb::ZOutOfMemory::ZOutOfMemory()':
  dbDatabase.cpp:(.text._ZN3odb12ZOutOfMemoryC2Ev[_ZN3odb12ZOutOfMemoryC5Ev]+0x14): undefined reference to `odb::ZException::ZException()'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbDatabase.cpp.o): In function `odb::ZIOError::~ZIOError()':
  dbDatabase.cpp:(.text._ZN3odb8ZIOErrorD2Ev[_ZN3odb8ZIOErrorD5Ev]+0x14): undefined reference to `odb::ZException::~ZException()'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbDatabase.cpp.o): In function `odb::dbOStream::write_error()':
  dbDatabase.cpp:(.text._ZN3odb9dbOStream11write_errorEv[_ZN3odb9dbOStream11write_errorEv]+0x39): undefined reference to `odb::ZIOError::ZIOError(int, char const*)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbDatabase.cpp.o): In function `odb::dbIStream::read_error()':
  dbDatabase.cpp:(.text._ZN3odb9dbIStream10read_errorEv[_ZN3odb9dbIStream10read_errorEv]+0x44): undefined reference to `odb::ZException::ZException(char const*, ...)'
  dbDatabase.cpp:(.text._ZN3odb9dbIStream10read_errorEv[_ZN3odb9dbIStream10read_errorEv]+0x4b): undefined reference to `odb::ZException::~ZException()'
  dbDatabase.cpp:(.text._ZN3odb9dbIStream10read_errorEv[_ZN3odb9dbIStream10read_errorEv]+0x8d): undefined reference to `odb::ZIOError::ZIOError(int, char const*)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbDatabase.cpp.o): In function `odb::ZOutOfMemory::~ZOutOfMemory()':
  dbDatabase.cpp:(.text._ZN3odb12ZOutOfMemoryD2Ev[_ZN3odb12ZOutOfMemoryD5Ev]+0x14): undefined reference to `odb::ZException::~ZException()'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `_getBits':
  logger.cpp:(.text+0x4b): undefined reference to `Tcl_AppendResult'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `_getCompileTime':
  logger.cpp:(.text+0x8d): undefined reference to `Tcl_AppendResult'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `_getCPUTime':
  logger.cpp:(.text+0x152): undefined reference to `Tcl_AppendResult'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_allocMem(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0x3f8): undefined reference to `Tcl_GetIntFromObj'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_enableMemCount(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0x518): undefined reference to `Tcl_GetIntFromObj'
  logger.cpp:(.text+0x549): undefined reference to `Tcl_GetDoubleFromObj'
  logger.cpp:(.text+0x5a5): undefined reference to `odb::AthSignalInstaller(int, void (*)(int))'
  logger.cpp:(.text+0x5db): undefined reference to `odb::AthMemCounter(int)'
  logger.cpp:(.text+0x5e8): undefined reference to `odb::AthSignalInstaller(int, void (*)(int))'
  logger.cpp:(.text+0x614): undefined reference to `odb::AthMemCounterp(int)'
  logger.cpp:(.text+0x621): undefined reference to `odb::AthSignalInstaller(int, void (*)(int))'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_setVerbose(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0x6e3): undefined reference to `Tcl_GetIntFromObj'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_setDebug(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0x750): undefined reference to `Tcl_GetString'
  logger.cpp:(.text+0x767): undefined reference to `Tcl_GetString'
  logger.cpp:(.text+0x77e): undefined reference to `Tcl_GetString'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_startTimer(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0xdbd): undefined reference to `Tcl_AppendResult'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_showTimer(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0xe11): undefined reference to `Tcl_GetString'
  logger.cpp:(.text+0xe28): undefined reference to `Tcl_GetString'
  logger.cpp:(.text+0xe3f): undefined reference to `Tcl_GetString'
  logger.cpp:(.text+0xe61): undefined reference to `Tcl_GetIntFromObj'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_resetTimer(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0xed7): undefined reference to `Tcl_GetIntFromObj'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_getTimer(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0xf40): undefined reference to `Tcl_GetIntFromObj'
  logger.cpp:(.text+0xf90): undefined reference to `Tcl_AppendResult'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_getCWToken(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0xfea): undefined reference to `Tcl_AppendResult'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::_setWarnCount(void*, Tcl_Interp*, int, Tcl_Obj* const*)':
  logger.cpp:(.text+0x1181): undefined reference to `Tcl_GetString'
  logger.cpp:(.text+0x11a3): undefined reference to `Tcl_GetIntFromObj'
  logger.cpp:(.text+0x11c1): undefined reference to `Tcl_GetIntFromObj'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::Logger::initLogger(Tcl_Interp*)':
  logger.cpp:(.text+0x124a): undefined reference to `Tcl_CreateObjCommand'
  logger.cpp:(.text+0x126f): undefined reference to `Tcl_CreateObjCommand'
  logger.cpp:(.text+0x1294): undefined reference to `Tcl_CreateObjCommand'
  logger.cpp:(.text+0x12b9): undefined reference to `Tcl_CreateObjCommand'
  logger.cpp:(.text+0x12e2): undefined reference to `Tcl_CreateObjCommand'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o):logger.cpp:(.text+0x130b): more undefined references to `Tcl_CreateObjCommand' follow
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::idle(int)':
  logger.cpp:(.text+0x14c0): undefined reference to `odb::ZInterface::idle(int)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::debug(char const*, char const*, char const*, ...)':
  logger.cpp:(.text+0x1916): undefined reference to `odb::ZInterface::notice(int, char const*, ...)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::milos(int, char const*, ...)':
  logger.cpp:(.text+0x1ceb): undefined reference to `odb::ZInterface::event(char const*, char const*, char const*, ...)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::ade(int, char const*, ...)':
  logger.cpp:(.text+0x1e6b): undefined reference to `odb::ZInterface::event(char const*, char const*, char const*, ...)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::notice(int, char const*, ...)':
  logger.cpp:(.text+0x2000): undefined reference to `odb::ZInterface::event(char const*, char const*, char const*, ...)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::verbose(int, char const*, ...)':
  logger.cpp:(.text+0x21ad): undefined reference to `odb::ZInterface::event(char const*, char const*, char const*, ...)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::info(int, char const*, ...)':
  logger.cpp:(.text+0x2365): undefined reference to `odb::ZInterface::event(char const*, char const*, char const*, ...)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o):logger.cpp:(.text+0x251d): more undefined references to `odb::ZInterface::event(char const*, char const*, char const*, ...)' follow
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::Logger::Logger(Tcl_Interp*)':
  logger.cpp:(.text._ZN3odb6LoggerC2EP10Tcl_Interp[_ZN3odb6LoggerC5EP10Tcl_Interp]+0x18): undefined reference to `odb::ZInterface::ZInterface()'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o): In function `odb::Logger::~Logger()':
  logger.cpp:(.text._ZN3odb6LoggerD2Ev[_ZN3odb6LoggerD5Ev]+0x26): undefined reference to `odb::ZInterface::~ZInterface()'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(logger.cpp.o):(.data.rel.ro._ZTIN3odb6LoggerE[_ZTIN3odb6LoggerE]+0x10): undefined reference to `typeinfo for odb::ZInterface'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbBlock.cpp.o): In function `odb::dbBlock::findSomeMaster(char const*, std::vector<odb::dbMaster*, std::allocator<odb::dbMaster*> >&)':
  dbBlock.cpp:(.text+0x9928): undefined reference to `Ath__parser::Ath__parser()'
  dbBlock.cpp:(.text+0x9944): undefined reference to `Ath__parser::mkWords(char const*, char*)'
  dbBlock.cpp:(.text+0x9957): undefined reference to `Ath__parser::getWordCnt()'
  dbBlock.cpp:(.text+0x9972): undefined reference to `Ath__parser::get(int)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbBlock.cpp.o): In function `odb::dbBlock::findSomeNet(char const*, std::vector<odb::dbNet*, std::allocator<odb::dbNet*> >&)':
  dbBlock.cpp:(.text+0x9a77): undefined reference to `Ath__parser::Ath__parser()'
  dbBlock.cpp:(.text+0x9a93): undefined reference to `Ath__parser::mkWords(char const*, char*)'
  dbBlock.cpp:(.text+0x9aa6): undefined reference to `Ath__parser::getWordCnt()'
  dbBlock.cpp:(.text+0x9ac5): undefined reference to `Ath__parser::get(int)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbBlock.cpp.o): In function `odb::dbBlock::findSomeInst(char const*, std::vector<odb::dbInst*, std::allocator<odb::dbInst*> >&)':
  dbBlock.cpp:(.text+0x9c19): undefined reference to `Ath__parser::Ath__parser()'
  dbBlock.cpp:(.text+0x9c35): undefined reference to `Ath__parser::mkWords(char const*, char*)'
  dbBlock.cpp:(.text+0x9c48): undefined reference to `Ath__parser::getWordCnt()'
  dbBlock.cpp:(.text+0x9c67): undefined reference to `Ath__parser::get(int)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbBlock.cpp.o): In function `odb::dbBlock::saveLef(char*)':
  dbBlock.cpp:(.text+0xeaf8): undefined reference to `odb::lefout::writeTechAndLib(odb::dbLib*, char const*)'
  /home/muktadir/cse220/OpenDB/build/src/db/libopendb.a(dbBlock.cpp.o): In function `odb::dbBlock::saveDef(char*, char*)':
  dbBlock.cpp:(.text+0xebbb): undefined reference to `odb::defout::defout()'
  dbBlock.cpp:(.text+0xec07): undefined reference to `odb::defout::selectNet(odb::dbNet*)'
  dbBlock.cpp:(.text+0xec24): undefined reference to `odb::defout::writeBlock(odb::dbBlock*, char const*)'
  dbBlock.cpp:(.text+0xec54): undefined reference to `odb::defout::~defout()'
  dbBlock.cpp:(.text+0xec81): undefined reference to `odb::defout::~defout()'
  collect2: error: ld returned 1 exit status
  Makefile:7: recipe for target 'app' failed
  make: *** [app] Error 1

**Comment by maliberty** [comment]
Since you are building this without using CMake you need to link with the additional libraries specified in https://github.com/The-OpenROAD-Project/OpenDB/blob/openroad/src/db/CMakeLists.txt

target_link_libraries(opendb
    PUBLIC
        zutil 
        zlib 
        tm
        lef
        defin
        defout
        lefout
        zutil
        lefin
    PRIVATE
        tcl
)
