### ISSUE TITLE
CMake tests tcl issue

### ISSUE THREAD

**Issue by arlpetergadfort** [The-OpenROAD-Project/OpenDB#132]
I've needed to comment out this test addition because it uses an issue on non-standard installs with TCL. But since this is a test, shouldn't this directory only be included when compiling for debugging?

https://github.com/The-OpenROAD-Project/OpenDB/blob/c095760fc6e8cf5fa99abe10f9401f8aa0e7a6eb/CMakeLists.txt#L36

Thanks,
Peter

**Comment by maliberty** [comment]
No, we test production builds as well.  If you need help with tcl please provide more details.

**Comment by arlpetergadfort** [comment]
It took me a while to get back to looking into the issue. The error is that is cannot link tcl because it cannot find the libtcl.so file.
I think the issue is that this CMakeLists for test1 assumes tcl is installed in a system directory (while the test of OpenROAD allows it to be installed anywhere).
I changed the line linked here from "tcl" to "${TCL_LIBRARY}" and now it compiles without issue:
https://github.com/The-OpenROAD-Project/OpenDB/blob/73a3d5db3c54a983e19587364e8b063bbed16615/tests/cpp/CMakeLists.txt#L13

**Comment by maliberty** [comment]
There is no 'test1' in tests/cpp.  Would you include a build log showing the issue.

**Comment by arlpetergadfort** [comment]
It appears the tests have been updated. But the issue is still there. I'm not sure how to attach the full log, but this is the step that is chokes on:
[ 99%] Linking CXX executable TestGeom
cd /data/OpenROAD/OpenROAD-flow/tools/build/OpenROAD/src/OpenDB/tests/cpp && cmake -E cmake_link_script CMakeFiles/TestGeom.dir/link.txt --verbose=1
g++  -O3 -DNDEBUG   CMakeFiles/TestGeom.dir/TestGeom.cpp.o  -o TestGeom  ../../src/db/libopendb.a ../../src/zutil/libzutil.a ../../src/zlib/libzlib.a ../../src/tm/libtm.a /data/OpenROAD/OpenROAD-flow/tools/OpenROAD/src/OpenDB/src/lef/lib/liblef.a ../../src/defin/libdefin.a ../../src/defout/libdefout.a ../../src/lefout/liblefout.a ../../src/lefin/liblefin.a -ltcl /data/OpenROAD/OpenROAD-flow/tools/OpenROAD/src/OpenDB/src/def/lib/libdef.a ../../src/zutil/libzutil.a /data/OpenROAD/OpenROAD-flow/tools/OpenROAD/src/OpenDB/src/lef/lib/liblef.a 
/usr/bin/ld: cannot find -ltcl
collect2: error: ld returned 1 exit status
make[2]: *** [src/OpenDB/tests/cpp/CMakeFiles/TestGeom.dir/build.make:119: src/OpenDB/tests/cpp/TestGeom] Error 1
make[2]: Leaving directory '/data/OpenROAD/OpenROAD-flow/tools/build/OpenROAD'
make[1]: *** [CMakeFiles/Makefile2:1802: src/OpenDB/tests/cpp/CMakeFiles/TestGeom.dir/all] Error 2
make[1]: Leaving directory '/data/OpenROAD/OpenROAD-flow/tools/build/OpenROAD'
make: *** [Makefile:153: all] Error 2

Note that it is unable to link tcl because there is no `-L` included that points to a non-standard TCL.

Below I've changed the CMakeLists.txt from `tcl` to `${TCL_LIBRARY}` and now it includes the tcl library in the linking (but boost seems to fail in linking).
[ 99%] Linking CXX executable TestGeom
cd /data/OpenROAD/OpenROAD-flow/tools/build/OpenROAD/src/OpenDB/tests/cpp && cmake -E cmake_link_script CMakeFiles/TestGeom.dir/link.txt --verbose=1
g++  -O3 -DNDEBUG   CMakeFiles/TestGeom.dir/TestGeom.cpp.o  -o TestGeom   -L{path-to-tcl}/lib  -Wl,-rpath,{path-to-tcl}/lib ../../src/db/libopendb.a ../../src/zutil/libzutil.a ../../src/zlib/libzlib.a ../../src/tm/libtm.a /data/OpenROAD/OpenROAD-flow/tools/OpenROAD/src/OpenDB/src/lef/lib/liblef.a ../../src/defin/libdefin.a ../../src/defout/libdefout.a ../../src/lefout/liblefout.a ../../src/lefin/liblefin.a -ltcl /data/OpenROAD/OpenROAD-flow/tools/OpenROAD/src/OpenDB/src/def/lib/libdef.a ../../src/zutil/libzutil.a /data/OpenROAD/OpenROAD-flow/tools/OpenROAD/src/OpenDB/src/lef/lib/liblef.a -ltcl 
CMakeFiles/TestGeom.dir/TestGeom.cpp.o: In function `_ZN5boost9unit_test9framework5state17execute_test_treeEmmPKNS2_23random_generator_helperE.isra.0':
TestGeom.cpp:(.text+0x20609): undefined reference to `clock_gettime'
CMakeFiles/TestGeom.dir/TestGeom.cpp.o: In function `boost::unit_test::timer::timer::elapsed() const':
TestGeom.cpp:(.text._ZNK5boost9unit_test5timer5timer7elapsedEv[_ZNK5boost9unit_test5timer5timer7elapsedEv]+0x31): undefined reference to `clock_gettime'

If these files are insufficient, we can continue over email, so I can share more details.

Thanks,
Peter

**Comment by maliberty** [comment]
I've made the change you suggest.  It looks like the FindTCL code is old and doesn't support the more modern module style.  This change will appear in the repo with some delay as we do internal testing first.
