### ISSUE TITLE
Missing find_package(spdlog REQUIRED) in CMakeLists.txt

### ISSUE THREAD

**Issue by sheiny** [The-OpenROAD-Project/OpenDB#137]
Recently, a spdlog library was added:
https://github.com/The-OpenROAD-Project/OpenDB/blob/0c53d7f2fab98f4ba50a63767ca73c3c1e82583e/Dockerfile#L54
https://github.com/The-OpenROAD-Project/OpenDB/blob/0c53d7f2fab98f4ba50a63767ca73c3c1e82583e/include/opendb/Logger.h#L34-L36
However, this library is not required by CMakeLists.txt

Please let me know if you need more information.

Thanks,
Sheiny

**Comment by osamahammad21** [comment]
@maliberty this needs to be closed
