### ISSUE TITLE
Testcases for extracting design data using the TCL interface

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#16]
The enclosed testcase.tgz includes data and unit tests to be added to OpenDB.

The library data is based on the nangate45 open library

The first testcase, gcd_def_access_checks.tcl looks at floorplan.def. 43 out of 54 tests pass in this suite.

The second testcase, gcd_pdn_def_access_checks.tcl looks at gcd_pdn.def. 50 out of 69 tests pass in this suite

[testcase.tar.gz](https://github.com/The-OpenROAD-Project/OpenDB/files/3775080/testcase.tar.gz)

**Comment by ahmed-agiza** [comment]
Thanks, will address them shortly.

**Comment by ahmed-agiza** [comment]
Few comments regarding these test cases:
1. The **floorplan.def** file seemed to be wrongly written (i.e. stated number of components is different from the actual number), I re-wrote it and updated the test cases accordingly.
2.  It seems hard to ditch the "NULL" representation for NULL pointers and it is likely to break some functions too (as this is SWIG's representation for null pointers in TCL), so we will leave it like this for now.
3. The die area function returns a rectangle, so I updated the test case accordingly.
4. I added a one-to-one mapping for all database enums to TCL strings, i.e. dbOnOffType is ["ON, OFF"] in TCL, dbTechLayerDir is NONE, [VERTICAL, HORIZONTAL..etc] 
5. The dbOrientTypes are [R0, R90, R180, R270, MY, MYR90, MX, MXR90], so I updated the test cases accordingly.
6. The getViaParams returns a dbViaParams object which is an object not a list, I updated the test case accordingly.
7.  The "net num wires" & "net num global wire" return 1, do you think this wrong?
8. The dbWireType is [NONE, COVER, FIXED, ROUTED, SHIELD, NOSHIELD], the [POWER, GROUND..etc] are signal types, I updated the test accordingly too.
