### ISSUE TITLE
How can I add wires to a net using the TCL interface?

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#17]
I can create a net using dbCreateNet e.g. 
set net [dbCreateNet $block "VDD"]

Normally I use $net getSWires to examine the set of wire segments for this net, but how do I add a wire segment to the net?

**Comment by Colin-Holehouse** [comment]
correction - the command I use to create a net is
dbNet_create $block "VDD"

**Comment by Colin-Holehouse** [comment]
dbSWire_create has the following prototype

Possible C/C++ prototypes are:
    odb::dbSWire::create(odb::dbNet *,dbWireType,odb::dbNet *)
    odb::dbSWire::create(odb::dbNet *,dbWireType)

But how do I setup the required dbWireType value?

**Comment by ahmed-agiza** [comment]
I am working on supporting all the fb enumerations in TCL, this should support this action and #18 too.
