### ISSUE TITLE
What is the sequence of commands that are needed to create wires using TCL

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#21]
An example of how wires should be constructed in the database would be very helpful - its not intuitive from just looking at the names of the functions that are available.

**Comment by ahmed-agiza** [comment]
Attached is a sample test case that will be integrated with the upcoming iteration. 

[12-wire_encoder.zip](https://github.com/The-OpenROAD-Project/OpenDB/files/3781461/12-wire_encoder.zip)
