### ISSUE TITLE
Cannot set viaParams on a via using TCL

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#25]
The TCL function dbVia_setViaParams doesn't accept enough arguments, so I'm unable to set the via parameters

% $block getVias
_a0b0839e267f0000_p_odb__dbVia
% set via _a0b0839e267f0000_p_odb__dbVia
_a0b0839e267f0000_p_odb__dbVia
% $via hasParams
0
% set params [$via getViaParams]
_b048730100000000_p_odb__dbViaParams
% $params setNumCutRows 3
% $params getNumCutRows
3
% [$via getViaParams] getNumCutRows
1
% $via hasParams
0
% $via setViaParams $params
Wrong # args.:dbVia_setViaParams self  argument 2

Clearly [$via getViaParams] is returning a copy of the viaParams object. This being the case, I need to be able to set the params to a modified set by calling the $via setViaParams function - however, this function does not accept a dbViaParams object as an argument.

**Comment by Colin-Holehouse** [comment]
This seems to work correctly in the develop branch now - I have submitted some tests under a different issue. From my point of view this issue can be considered resolved and fixed.

**Comment by ahmed-agiza** [comment]
I pushed a fix in #27, but was not sure about the test case, thanks for your feedback.
