### ISSUE TITLE
TCL function dbRow_create does not set direction or orientation correctly

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#26]
The test creates some rows with various settings for direction and orientation. Examining the row settings immediately aferwards shows that the values are incorrect.

[opendb_row_settings_test.tcl.gz](https://github.com/The-OpenROAD-Project/OpenDB/files/3789647/opendb_row_settings_test.tcl.gz)

**Comment by ahmed-agiza** [comment]
Thanks, it is addressed in [ed626d6](https://github.com/The-OpenROAD-Project/OpenDB/pull/27/commits/ed626d67b8787d6a7c1aa8b60e926af4b576a2dc).

**Comment by ahmed-agiza** [comment]
Resolved in #27.
