### ISSUE TITLE
DEF version

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#30]
If I try to set the version of DEF to be writteon out, I get:

ERROR: set defout version: Command {$def_writer setVersion DEF_5_6}
TypeError in method 'defout_setVersion', argument 2 of type 'odb::defout::Version'

I've updated one of the tests to include this check
[07-write_def_test.tcl.gz](https://github.com/The-OpenROAD-Project/OpenDB/files/3798349/07-write_def_test.tcl.gz)

The header of the def is:

% more ./OpenDB/build/test.def
VERSION 5.3 ;
NAMESCASESENSITIVE ON ;
DIVIDERCHAR "/" ;
BUSBITCHARS "[]" ;
DESIGN counter ;
UNITS DISTANCE MICRONS 1000 ;

the VERSION value is hardcoded in the defout code. (The version in the incoming DEF is 5.7, so unless otherwise modified by the user, this should be the default value used for the def out version as well)

**Comment by ahmed-agiza** [comment]
Addressed in #32.
