### ISSUE TITLE
Additional via checking

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#31]
I wrote some additional tests to examin vias that are created from via rules - the tests pass, so nothing to fix, but it would be good to incorporate the tests into the regression test suite.

[via_definition.tcl.gz](https://github.com/The-OpenROAD-Project/OpenDB/files/3798432/via_definition.tcl.gz)

**Comment by ahmed-agiza** [comment]
Thanks, I will incorporate it in the next update.

**Comment by ahmed-agiza** [comment]
Addressed in #32.
