### ISSUE TITLE
Read / Write of databases

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#33]
At the end of a session with the database I should be able to save the current database to a file, then I should be able to exit the tool, restart and load the database so that I'm back at the same position.

Currently all the examples are of the dbDatabase_create variety.

If I try to save a database with dbDatabase_write I get a type error

% $db write test.odb
TypeError in method 'dbDatabase_write', argument 2 of type 'FILE *'

For read:
% $db read test.odb
TypeError in method 'dbDatabase_read', argument 2 of type 'FILE *'

does this imply that I have to create a database in order to load a database?

**Comment by ahmed-agiza** [comment]
Yes, you have to create the database first in order to load a file, but there is probably some handling that I might need to check from the database side.

**Comment by abdelrahmanhosny** [comment]
Addressed in PR #34
