### ISSUE TITLE
Helper functions to read lef too restrictive

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#35]
It is not normal practice to concatenate LEF files together into a single file before reading into a tool. 

Normally there is a single LEF file that defines the technology - this file is specified first in a list of LEF files, and is read first in order to define all the layers etc. Subsequent LEF files are read and add cells to the library.

**Comment by ahmed-agiza** [comment]
I can remove the dbLib argument from the read_def command so you can then just:
read_lef $db f1.lef
read_lef $db f2.lef
read_def $db f3.def #This internally will call getLibs and pass it to the DEF parser.
What do you think?

**Comment by Colin-Holehouse** [comment]
Yes, I think this is the right solution.

**Comment by jjcherry56** [comment]
The commands in the OpenROAD implementation that I am working on work is more like what you are looking for. See README.md in the OpenStaDB repo. The whole concept of passing database objects to tcl commands is nonsense. As you say, there should be a current database that is an implicit arg to the UI commands. Anybody that wants to muck around with multiple databases will have to use lower level functions/commands.

**Comment by nefelus** [comment]
load_lef -file <file> assumes there is no technology read yet!
so this is how you read multiple lef files

load_lef -file tech.lef
load_lef -notech -file lef1.lef
load_lef -notech -file lef2.lef

**Comment by ahmed-agiza** [comment]
Addressed in #39.
