### ISSUE TITLE
Building for Red Hat

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#36]
I have "Red Hat Enterprise Linux Server release 6.9" - in order to make the build process work I need to add the line

add_link_options(-lrt)

into the CMakeLists.txt file. Tested this out on UCSD machines, and the build is still successful with that setting. Please can this option be added into the CMakeLists.txt file.

**Comment by ahmed-agiza** [comment]
Addressed in #39.

**Comment by Colin-Holehouse** [comment]
This fix seems to have been removed from the develop branch, - the cmake option -DLINK_RT=ON no longer works.

**Comment by rovinski** [comment]
@maliberty This is actually the same issue I was talking about. Incorporating this snippet in CMakeList.txt will fix it: 
https://github.com/The-OpenROAD-Project/OpenROAD/blob/2d41acd184d2fb5c551fbdb1f74bbe73a782de6f/src/CMakeLists.txt#L326-L333

**Comment by maliberty** [comment]
This is moot as I have removed the code that causes the problem
