### ISSUE TITLE
dbBlock_getParent on top block causes assertion falure

### ISSUE THREAD

**Issue by rovinski** [The-OpenROAD-Project/OpenDB#37]
According to the header comments in [db.h#L934](https://github.com/The-OpenROAD-Project/OpenDB/blob/3b815c77a4d3617179fec6abce6b58a5989a9a15/include/opendb/db.h#L934):
```   ///
    /// Get the parent block this block. Returns NULL if this block is the
    /// top-block of the chip.
    ///
    dbBlock * getParent();
````
However, when getting the parent of a top-level block in the tcl shell, it causes an assertion failure and crashes the shell:
```
opendbtcl: /OpenDB/src/db/dbTable.h:126: T* odb::dbTable<T>::getPtr(uint) const [with T = odb::_dbBlock; uint = unsigned int]: Assertion `(id != 0) && (page < _page_cnt)' failed.
Aborted (core dumped)
```
I would expect the function to return NULL or gracefully error. Is this the expected behavior?

A code snippet which will reproduce the crash:
```
set db [dbDatabase_create]
set lef_parser [new_lefin $db true]
set def_parser [new_defin $db]
set lib [lefin_createTechAndLib $lef_parser gscl45nm ./OpenDB/tests/data/gscl45nm.lef]
set chip [$def_parser createChip {$lib} ./OpenDB/tests/data/design.def]
set block [dbChip_getBlock $chip]
dbBlock_getParent $block
```

**Comment by ahmed-agiza** [comment]
Yeah, I believe the comment is wrong here, checking the source code it seems like an expected behavior, dbTable getPtr method throws an error if when it fails to retrieve a valid dbObject.
