### ISSUE TITLE
Access to DEF properties from TCL

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#48]
There are some properties stored in the DEF that I need to get access to from the TCL interface, but it's unclear how I would go about accessing them.

% dbProperty_getProperties
Wrong number of arguments :dbProperty_getProperties object  argument 1
% dbProperty_getProperties $block
TypeError in method 'dbProperty_getProperties', argument 1 of type 'dbObject *'
% dbProperty_getProperties $db
TypeError in method 'dbProperty_getProperties', argument 1 of type 'dbObject *'

Is there some additional SWIG support required for properties?

**Comment by ahmed-agiza** [comment]
This requires SWIG support, will address it soon.

**Comment by Colin-Holehouse** [comment]
I think I have enough information now to work with properties
