### ISSUE TITLE
How do I remove design elements from a design using TCL?

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#49]
There are some use cases where it is necessary to be able to delete objects from the database. For example, the PDN module inserts a power grid for the design, but this will clash with any existing nets defined in the incoming database.

There is a -delete function on many of the objects, however, this seems to delete the TCL object and doesnt affect the underlying database.

I am not blocked by this issue, as I can massage my incoming testcases - removing offending objects in my input DEF before loading into a database, so I would consider it "low" priority.

**Comment by ahmed-agiza** [comment]
There is a static `destroy` method for most database objects, so if you have a net object $n you can call `dbNet_destroy $n`
Feel free to close the issue if this works for you.

**Comment by Colin-Holehouse** [comment]
Thanks, the destroy method seems to be what I'm looking for. I'll experiment with using this and close this issue.
