### ISSUE TITLE
TCL command dbChip_create does not create a chip object

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/OpenDB#57]
The code:
```
set db [dbDatabase_create]
dbChip_create $db
```

does not create a ```chip``` object, returning NULL instead.
A chip object needs to be passed to dbBlock_create to allow a ```block``` object to be created

**Comment by ahmed-agiza** [comment]
Not really, you just need to make sure you read a LEF file before attempting to create a chip.

**Comment by Colin-Holehouse** [comment]
Makes sense - would be nicer if the command reported this as an error
