### ISSUE TITLE
"+SOURCE XXXX" is dropped in DEF's components (on develop branch; with lef/def58 enablements)

### ISSUE THREAD

**Issue by mgwoo** [The-OpenROAD-Project/OpenDB#71]
I've found out that the following nangate45 cases show this problem:
[filler_source_test.tar.gz](https://github.com/The-OpenROAD-Project/OpenDB/files/3954078/filler_source_test.tar.gz)

commit: https://github.com/The-OpenROAD-Project/OpenDB/commit/5fc66c308cb6bdbd9f513f6202be300b7ace763b

I only used odb_read_lef, odb_read_def and odb_write_def, but the generated DEF doesn't have "+ SOURCE DIST" statements.
This caused a failure to OpenDP JenkinsCI testcases on the integrated top-level repo.

Could you check this problem?

**Comment by jjcherry56** [comment]
fixed by 7d268f494ce497751fd9340c6e6f36166dda518a
