### ISSUE TITLE
readLef in Lefin for c++

### ISSUE THREAD

**Issue by Michael-JY-He** [The-OpenROAD-Project/OpenDB#78]
Hi I'm a student from UT Austin and I'm trying to use OpenDB to read Lef/Def for my router which is in C++.
My understanding of using it is:
dbDatabase db;
lefin lef(&db, false);
defin def(&db);
lef.readLef(lefFileName);
def.createChip(.....);
etc.
My question is, the readLef function in lefin is private. I'm unable to call it. Should it be public?
Could you please provide a simple example just to show how to read and write LEF/DEF?

**Comment by maliberty** [comment]
I'm just learning this system but it looks like you want one of the create
methods: createTech, createLib, createTechAndLib.  It looks like the choice
depends on the tech of lef data you are loading.

Matt

**Comment by ahmed-agiza** [comment]
You can find some examples of these APIs in this TCL wrappers file. https://github.com/The-OpenROAD-Project/OpenDB/blob/master/src/swig/tcl/dbhelpers.i
